punctuation_dict = {
    "...": True,
    "{": True,
    "}": True,
    "[": True,
    "]": True,
    ")": True,
    "(": True,
    ">": True,
    "<": True,
    "'": True,
    "\"": True,
    ":": True,
    ";": True,
    "!": True,
    "#": True,
    "@": True,
    "-": True,
    "_": True,
    "?": True,
    "+": True,
    "^": True,
    "*": True,
    "%": True,
    ".": True,
}
